// GENERATED by scripts/promote-firmware.mjs — do NOT edit by hand.
// Pinned firmware builds the website ships, keyed by target platform. Bump a
// target with `npm run promote-firmware <target>` when a build is ready — never
// automatically. Each target's artifact is src/assets/<file> (extension varies by
// format: uf2 / hex / img / bin …).

/** Combined-UF2 build params — present only for the UF2 + spliced-littlefs model
 *  (RP2040 / RP2350). Other artifact formats omit this. */
export interface CombinedUf2 {
  /** UF2 family id for the assembler. */
  family: number
  /** littlefs block size / count + flash base the FS image is spliced into. */
  blockSize: number
  blockCount: number
  fsBase: number
}

export interface FirmwareRelease {
  /** Target platform id (matches the export DEVICES list). */
  target: string
  /** Human board name. */
  board: string
  /** Artifact type the target ships: 'uf2' | 'hex' | 'img' | 'bin' | … */
  format: string
  /** Asset filename in src/assets/ (extension matches `format`). */
  file: string
  /** What the device reports over VERSION — the site advertises the same string. */
  version: string
  /** Firmware source commit this build was promoted from. */
  commit: string
  /** Date promoted to the site (UTC, YYYY-MM-DD). */
  builtAt: string
  /** Artifact size in bytes. */
  bytes: number
  /** UF2 + littlefs params (UF2-family targets only). */
  combinedUf2?: CombinedUf2
}

export const FIRMWARE_RELEASES: Record<string, FirmwareRelease> = {
  "rp2040": {
    target: "rp2040",
    board: "Raspberry Pi Pico W (RP2040)",
    format: "uf2",
    file: "led-animator-rp2040.uf2",
    version: "rust-0.2",
    commit: "2c4620f",
    builtAt: "2026-07-19",
    bytes: 996352,
    combinedUf2: { family: 0xe48bff56, blockSize: 4096, blockCount: 212, fsBase: 0x1012c000 },
  },
}
