// GENERATED by scripts/promote-firmware.mjs — do NOT edit by hand.
// The pinned LED Animator RP2040 firmware the website ships. Bump it with a
// deliberate `npm run promote-firmware` when a new build is ready — never
// automatically. The UF2 itself is src/assets/led-animator-rp2040.uf2.
export const FIRMWARE_RELEASE = {
  /** What the device reports over VERSION — the site advertises the same string. */
  version: "rust-0.1",
  /** firmware-rust source commit this build was promoted from. */
  commit: "a2f113c",
  /** Date the build was promoted to the site (UTC). */
  builtAt: "2026-07-15",
  /** UF2 size in bytes. */
  bytes: 985600,
  board: 'Raspberry Pi Pico W (RP2040)',
  // Flash / littlefs layout the export splices the FS image into. Read from
  // firmware-rust/src/fs.rs, so it can't drift from the firmware.
  blockSize: 4096,
  blockCount: 212,
  fsBase: 0x1012c000,
} as const
