// GENERATED by scripts/promote-firmware.mjs — do NOT edit by hand.
// Pinned firmware builds the website ships, keyed by target platform. Bump a
// target with `npm run promote-firmware <target>` when a build is ready — never
// automatically. Each target's UF2 is src/assets/led-animator-<target>.uf2.

export interface FirmwareRelease {
  /** Target platform id (matches the export DEVICES list). */
  target: string
  /** Human board name. */
  board: string
  /** What the device reports over VERSION — the site advertises the same string. */
  version: string
  /** Firmware source commit this build was promoted from. */
  commit: string
  /** Date promoted to the site (UTC, YYYY-MM-DD). */
  builtAt: string
  /** UF2 size in bytes. */
  bytes: number
  /** UF2 family id for the combined-image assembler. */
  uf2Family: number
  /** littlefs block size / count + flash base the FS image is spliced into. */
  blockSize: number
  blockCount: number
  fsBase: number
}

export const FIRMWARE_RELEASES: Record<string, FirmwareRelease> = {
  "rp2040": {
    target: "rp2040",
    board: "Raspberry Pi Pico W (RP2040)",
    version: "rust-0.1",
    commit: "433bbbf",
    builtAt: "2026-07-16",
    bytes: 985600,
    uf2Family: 0xe48bff56,
    blockSize: 4096,
    blockCount: 212,
    fsBase: 0x1012c000,
  },
}
