// Precompile the MicroPython player to leda.mpy and embed it as a base64 blob in
// src/export/firmwareMpy.generated.ts. Run after editing rp2040.ts:  npm run gen:mpy
//
// Requires mpy-cross matching the bundled MicroPython (pip install "mpy-cross==1.28.0rc0.post2").
// The .mpy is ARCHITECTURE-SPECIFIC (the player uses @micropython.viper -> native
// code): armv6m for RP2040 / Pico W. A Pico 2 W (RP2350) build would add its arch.
import { writeFileSync, readFileSync } from 'fs'
import { execFileSync } from 'child_process'
import { createHash } from 'crypto'
import { rp2040ModulePy } from './src/export/rp2040'

const ARCH = 'armv6m' // RP2040 / Pico W

let commit = 'nogit'
try {
  commit = execFileSync('git', ['rev-parse', '--short', 'HEAD']).toString().trim()
} catch {
  /* not a git checkout */
}
const build = `dev+${commit}`

// Compile the module-form source (no trailing main()) for the loader to import.
writeFileSync('/tmp/leda.py', rp2040ModulePy(build))
execFileSync('python3', ['-m', 'mpy_cross', '-march=' + ARCH, '-o', '/tmp/leda.mpy', '/tmp/leda.py'])
const mpy = readFileSync('/tmp/leda.mpy')
const b64 = mpy.toString('base64')

// Version-neutral source hash: catches firmware-LOGIC changes (staleness) without
// tripping on every new commit (the build id alone must not invalidate the blob).
const sourceSha = createHash('sha256').update(rp2040ModulePy('__VERSION__')).digest('hex')

const out = `// GENERATED by gen-mpy.ts — DO NOT EDIT. Run \`npm run gen:mpy\` after editing rp2040.ts.
// Precompiled MicroPython player (leda.mpy) for ${ARCH}, base64-encoded.
export const FIRMWARE_MPY = {
  arch: '${ARCH}',
  build: '${build}',
  sourceSha: '${sourceSha}',
  base64:
    '${b64}',
} as const

/** Decode the embedded leda.mpy blob to bytes (browser + node). */
export function firmwareMpyBytes(): Uint8Array {
  const bin = atob(FIRMWARE_MPY.base64)
  const bytes = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i)
  return bytes
}
`
writeFileSync('./src/export/firmwareMpy.generated.ts', out)
console.log(`wrote firmwareMpy.generated.ts: ${ARCH}, ${mpy.length} bytes mpy (${b64.length} b64 chars), build ${build}`)
